### ISSUE TITLE
Sunstone "Cloud View" defaults to the OpenNebula logo, rather than the custom logo.

### ISSUE THREAD

**Issue by greyspectrum** [fasrc/opennebula-puppet-module#12]
In `opennebula-puppet-module/templates/5.2`, there is no template for the "cloud view." The other views have templates with if/else logic to reference the custom logo at the top of the Sunstone dashboard.

Since no template is defined in Puppet, OpenNebula will just use the default template on the controller, with the default logo.

**Comment by jtriley** [comment]
Fixed by #13
